#ifndef PARADOX_SOFTWARE_C_HEADER_PLATFORM_CONSOLE
#define PARADOX_SOFTWARE_C_HEADER_PLATFORM_CONSOLE

#include <paradox-platform/defines.h>

#define PARADOX_CONSOLE_COLOR_RED     "\x1b[31m"
#define PARADOX_CONSOLE_COLOR_GREEN   "\x1b[32m"
#define PARADOX_CONSOLE_COLOR_YELLOW  "\x1b[33m"
#define PARADOX_CONSOLE_COLOR_BLUE    "\x1b[34m"
#define PARADOX_CONSOLE_COLOR_MAGENTA "\x1b[35m"
#define PARADOX_CONSOLE_COLOR_CYAN    "\x1b[36m"
#define PARADOX_CONSOLE_COLOR_RESET   "\x1b[0m"

#endif